### ISSUE TITLE
How to debug crashes when unbinding

### ISSUE THREAD

**Issue by paulclou** [bryansteiner/gpu-passthrough-tutorial#14]
Thanks for the great walk through. I am experiencing hard crashes of the host computer when shutting down the VM 1/20 times. I suspect I happens during unbinding from vfio and rebinding onto nouveau. When I reboot and open the syslog it shows a line fill of @ symbols. Anyway to pinpoint the cause?

**Comment by bryansteiner** [comment]
Hey sorry for not getting back to you sooner...
Here are some guides for debugging your libvirt setup:

- https://libvirt.org/kbase/debuglogs.html
- https://fedoraproject.org/wiki/How_to_debug_Libvirt_problems
