### ISSUE TITLE
alloc_hugepages.sh $MEMORY is not defined

### ISSUE THREAD

**Issue by pdc4444** [bryansteiner/gpu-passthrough-tutorial#15]
This command does not work because $MEMORY is not defined:

HUGEPAGES="$(($MEMORY/$(($(grep Hugepagesize /proc/meminfo | awk '{print $2}')/1024))))"

I assume you meant to add this as an configuration parameter in kvm.conf?

**Comment by bryansteiner** [comment]
Every one of my hook scripts starts with the source command which loads in kvm.conf:

`source /etc/libvirt/hooks/kvm.conf`

You'll notice my config file has memory defined on the second line.

**Comment by pdc4444** [comment]
@bryansteiner My sincere apologies. I know it might sound really dumb but when I went through your guide I didn't even look at your shared code I simply read the read.me and used the examples there to make my own scripts. Thanks for all your help by the way!

**Comment by bryansteiner** [comment]
Don't even worry about it. It's because of people like you who decide to provide feedback that this guide came to exist so I'm thankful for all the input. Good luck with your build!
