### ISSUE TITLE
CPU pinning logical/physical indices

### ISSUE THREAD

**Issue by tomlankhorst** [bryansteiner/gpu-passthrough-tutorial#19]
I played around with the CPU pinning configuration. Here's the `lstopo` for _Ryzen 9 3950X_:

![lstopo](https://user-images.githubusercontent.com/675432/107151073-fac62a80-6960-11eb-9085-a0a9654ba5af.png)

I followed your suggestion of mapping CPU indices such that a core and its siblings will be passed together with **physical** indices. I.e:
```xml
  <cputune>                        
    <vcpupin vcpu='0' cpuset='4'/> 
    <vcpupin vcpu='1' cpuset='20'/> 
    <vcpupin vcpu='2' cpuset='5'/>
    <vcpupin vcpu='3' cpuset='21'/>
    <!-- etc -->
```
_Pass Core L#4 as vcpu 0,1, Core L#4 as vcpu 2,3, etc._

However. When running Geekbench on the VM, the multi-core performance was below expectation.
For comparison: setting vcpupin based on **logical** indices:

```xml
  <cputune>                        
    <vcpupin vcpu='0' cpuset='8'/> 
    <vcpupin vcpu='1' cpuset='9'/> 
    <vcpupin vcpu='2' cpuset='10'/>
    <vcpupin vcpu='3' cpuset='11'/>
    <!-- etc -->
```

![image](https://user-images.githubusercontent.com/675432/107151280-ff3f1300-6961-11eb-856f-c63bd0e68dc6.png)

That's a big multi-core performance hit. 
I believe that the CPU-pinning should be done with the `cpuset` value being the **logical** index instead.

**Comment by bryansteiner** [comment]
Hey sorry for the delayed response... 

First, let me refer you to this section of the [arch wiki page on cpu pinning](https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#CPU_pinning). Here you'll see the use of the command `lspcu -e`. The CPU threads are numbered on the leftmost "CPU" column and you can see which threads share the same physical core under the "CORE" column. Pretty much every tutorial on the subject will tell you to pin threads together by physical cores and not across different physical cores. In your modified example, you're pinning threads across different physical cores. This is simply not recommended anywhere and I'm genuinely surprised to see better performance numbers.

Let's say based on the CPU topography for your 3950X that I wanted to pass physical cores #8-15 (bottom row of `lstopo`) to the guest and leave #0-7 (top row of `lstopo`) to the host. This corresponds to passing 16 out of 32 logical threads to your VM. Here's what I'd expect your pinning configuration to look like:

```
<vcpu placement="static">16</vcpu>
<cputune>
    <vcpupin vcpu="0" cpuset="8"/>
    <vcpupin vcpu="1" cpuset="24"/>
    <vcpupin vcpu="2" cpuset="9"/>
    <vcpupin vcpu="3" cpuset="25"/>
    <vcpupin vcpu="4" cpuset="10"/>
    <vcpupin vcpu="5" cpuset="26"/>
    <vcpupin vcpu="6" cpuset="11"/>
    <vcpupin vcpu="7" cpuset="27"/>
    <vcpupin vcpu="8" cpuset="12"/>
    <vcpupin vcpu="9" cpuset="28"/>
    <vcpupin vcpu="10" cpuset="13"/>
    <vcpupin vcpu="11" cpuset="29"/>
    <vcpupin vcpu="10" cpuset="14"/>
    <vcpupin vcpu="11" cpuset="30"/>
    <vcpupin vcpu="10" cpuset="15"/>
    <vcpupin vcpu="11" cpuset="31"/>
<cputune>
```
Please go ahead and confirm whether your current configuration outperforms this one. I would not expect it to. I've gone ahead and edited the README for my tutorial to make the cpu pinning section easier to understand. Please report back with your results.

**Comment by bryansteiner** [comment]
Closing issue awaiting response

**Comment by tomlankhorst** [comment]
I must have made a mistake somewhere while editing the pinning since I can't reproduce the 'worse' results with your configuration anymore. Thanks for helping me out anyway!
