### ISSUE TITLE
Unable to complete install: 'Hook script execution failed: internal error: Child process 

### ISSUE THREAD

**Issue by jalsarraf0** [bryansteiner/gpu-passthrough-tutorial#23]
Hi there,

Great tutorial but I'm running into some issues. I have 2x 1080Ti's and gettings this error:

Unable to complete install: 'Hook script execution failed: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /etc/libvirt/hooks/qemu win10 prepare begin -) unexpected exit status 1: error: unknown command: 'nodedev-detach=pci_0000_04:00.0'
error: Could not find matching device 'pci_0000_04:00.1'
error: Node device not found: no node device with matching name 'pci_0000_04:00.1'
error: Could not find matching device 'pci_0000_00:14.0'
error: Node device not found: no node device with matching name 'pci_0000_00:14.0'
error: Could not find matching device 'pci_0000_00:03.2'
error: Node device not found: no node device with matching name 'pci_0000_00:03.2'
error: Could not find matching device 'pci_0000_05:00.0'
error: Node device not found: no node device with matching name 'pci_0000_05:00.0'
'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2089, in _do_async_install
    guest.installer_instance.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 542, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 491, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4034, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: Hook script execution failed: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /etc/libvirt/hooks/qemu win10 prepare begin -) unexpected exit status 1: error: unknown command: 'nodedev-detach=pci_0000_04:00.0'
error: Could not find matching device 'pci_0000_04:00.1'
error: Node device not found: no node device with matching name 'pci_0000_04:00.1'
error: Could not find matching device 'pci_0000_00:14.0'
error: Node device not found: no node device with matching name 'pci_0000_00:14.0'
error: Could not find matching device 'pci_0000_00:03.2'
error: Node device not found: no node device with matching name 'pci_0000_00:03.2'
error: Could not find matching device 'pci_0000_05:00.0'
error: Node device not found: no node device with matching name 'pci_0000_05:00.0'

Here are the way I have the three files you specified configured. Am I doing something wrong?

kvm.conf:

## Virsh devices
VIRSH_GPU_VIDEO=pci_04:00.0
VIRSH_GPU_AUDIO=pci_04:00.1
VIRSH_GPU_USB=pci_00:14.0
VIRSH_GPU_SERIAL=pci_00:03.2
VIRSH_NVME_SSD=pci_05:00.0

bind_vfio.sh:

#!/bin/bash

## Load the config file
source "/etc/libvirt/hooks/kvm.conf"

## Load vfio
modprobe vfio
modprobe vfio_iommu_type1
modprobe vfio_pci

## Unbind gpu from nvidia and bind to vfio
virsh nodedev-detach=pci_0000_04:00.0
virsh nodedev-detach=pci_0000_04:00.1
virsh nodedev-detach=pci_0000_00:14.0
virsh nodedev-detach=pci_0000_00:03.2
## Unbind ssd from nvme and bind to vfio
virsh nodedev-detach=pci_0000_05:00.0

unbind.vfio.sh

#!/bin/bash

## Load the config file
source "/etc/libvirt/hooks/kvm.conf"

## Unbind gpu from vfio and bind to nvidia
virsh nodedev-reattach=pci_0000_04:00.0
virsh nodedev-reattach=pci_0000_04:00.1
virsh nodedev-reattach=pci_0000_00:14.0
virsh nodedev-reattach=pci_0000_00:03.2
## Unbind ssd from vfio and bind to nvme
virsh nodedev-reattach=pci_0000_05:00.0

## Unload vfio
modprobe -r vfio_pci
modprobe -r vfio_iommu_type1
modprobe -r vfio

For reference these are the devices I'm trying to passthrough:

GPU with HMDI Audio:

04:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: eVga.com. Corp. GP102 [GeForce GTX 1080 Ti]
	Physical Slot: 4-1
	Flags: bus master, fast devsel, latency 0, IRQ 85, NUMA node 0, IOMMU group 35
	Memory at f8000000 (32-bit, non-prefetchable) [size=16M]
	Memory at 383fc0000000 (64-bit, prefetchable) [size=256M]
	Memory at 383fd0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at d000 [size=128]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

04:00.1 Audio device: NVIDIA Corporation GP102 HDMI Audio Controller (rev a1)
	Subsystem: eVga.com. Corp. GP102 HDMI Audio Controller
	Physical Slot: 4-1
	Flags: bus master, fast devsel, latency 0, IRQ 73, NUMA node 0, IOMMU group 35
	Memory at f9080000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

USB:

00:14.0 USB controller: Intel Corporation C610/X99 series chipset USB xHCI Host Controller (rev 05) (prog-if 30 [XHCI])
	Subsystem: Micro-Star International Co., Ltd. [MSI] C610/X99 series chipset USB xHCI Host Controller
	Flags: bus master, medium devsel, latency 0, IRQ 19, NUMA node 0, IOMMU group 22
	Memory at 383ffff00000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci

Serial: 

00:03.2 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 3 (rev 02) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 30, NUMA node 0, IOMMU group 16
	Bus: primary=00, secondary=04, subordinate=04, sec-latency=0
	I/O behind bridge: 0000d000-0000dfff [size=4K]
	Memory behind bridge: f8000000-f90fffff [size=17M]
	Prefetchable memory behind bridge: 0000383fc0000000-0000383fd1ffffff [size=288M]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

NVME:

05:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 (prog-if 02 [NVM Express])
	Subsystem: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
	Flags: bus master, fast devsel, latency 0, IRQ 16, NUMA node 0, IOMMU group 36
	Memory at fb800000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: nvme
	Kernel modules: nvme

I know it must be some small silly mistake I'm making or maybe I'm just not understanding how this works. I'm new to VMs on Linux and passthrough and I am dying to play Tarkov (as it is the only game that I play on Windows). Thanks for your help!

Edit: If you need to see everything on my system I'm willing to dump it here too.

Edit 2: Used the correct addresses and still no dice.

**Comment by Moonlight63** [comment]
You are mixing some nomenclature. The error appears to be in the first command.
`unexpected exit status 1: error: unknown command: 'nodedev-detach=pci_0000_04:00.0'`
Most likely, the command you are looking for is `virsh nodedev-detach pci_0000_04_00_1`
Ditto for the rest of the addresses.

The issue is that the nodedev-detach/reattach command replaces colons and dots with underscores. Also, there is no equal sign.
