### ISSUE TITLE
Problems since new Kernels

### ISSUE THREAD

**Issue by Gamerios** [bryansteiner/gpu-passthrough-tutorial#29]
Hello,

Ubuntut 20.04 and QEMU Virt-Manager - Nested virtualization suddenly doesnt work

Since Yesterday when i want start Windows 10 VM in Ubuntu 20.04 and QEMU 4.2.1 also tryed 5.2 and 6.2 and latest

i get this error:

Code:

qemu-system-x86_64: error: failed to set MSR 0x48f to 0xffffff00036dfb
qemu-system-x86_64: /home/user/qemu-4.2.1/target/i386/kvm.c:2691: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.

i have kvm ignore_msrs=1 and so on tryed ON and OFF like before it worked in XML

Code:

<cpu mode="host-passthrough" check="none" migratable="on">
    <topology sockets="1" dies="1" cores="11" threads="2"/>
    <cache mode="passthrough"/>
    <feature policy="require" name="hypervisor"/>
    <feature policy="disable" name="mpx"/>
    <feature policy="require" name="ibpb"/>
    <feature policy="require" name="md-clear"/>
    <feature policy="require" name="spec-ctrl"/>
    <feature policy="require" name="ssbd"/>
    <feature policy="require" name="invtsc"/>
  </cpu>

Anyone can help it worked now for years but now not anymore since apt update and apt upgrade need downgrade Ubuntu Linux Kernel?

i need CPU Host-Passthrough otherwise Windows 10 has no good performance like in all Windows 10 Gaming VM GPU Passthrough Tutorials stand and also i tested

Hope any one can help here also GRUB

Code:

 GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_iommu=on kvm.ignore_msrs=1 video=efifb:off vfio-pci.ids=10de:2486,10de:228b,10de:2503,10de:228e isolcpus=3-13,17-27 nohz_full=3-13,17-27 rcu_nocbs=3-13,17-27 msr.allow_writes=on kvm.intel_nested=1"

A and
Ubuntu Linux Kernel
5.11.0-43-generic

and when start MacOS VM also with CPU Host-Passthrough it work witout an Error hmm

Thank ya
Kind Regards

**Comment by bryansteiner** [comment]
Sorry for the long delay with no response. This just isn't an issue I'm familiar with. 
Have you attempted the following solution?
https://github.com/GNS3/gns3-server/issues/1774#issuecomment-639396742

**Comment by bryansteiner** [comment]
Closing since no response and the issue was already raised here ([GNS3/gns3-server](https://github.com/GNS3/gns3-server/issues/1774)) where it is more likely to be answered
