### ISSUE TITLE
alloc_hugepages.sh error

### ISSUE THREAD

**Issue by Hamza-H-allaham** [bryansteiner/gpu-passthrough-tutorial#34]
hi
when i run alloc_hugepages.sh :

./alloc_hugepages.sh: line 7: /2: syntax error: operand expected (error token is "/2")
Allocating hugepages...
./alloc_hugepages.sh: line 10: echo: write error: Invalid argument
./alloc_hugepages.sh: line 14: ((: 0 !=  && 0 < 1000 : syntax error: operand expected (error token is "&& 0 < 1000 ")

**Comment by bryansteiner** [comment]
The error output here is pointing to line 7 as being the issue:
`## Calculate number of hugepages to allocate from memory (in MB)
HUGEPAGES="$(($MEMORY/$(($(grep Hugepagesize /proc/meminfo | awk '{print $2}')/1024))))"`

Do you have MEMORY variable defined in your kvm.conf?
See [here](https://github.com/bryansteiner/gpu-passthrough-tutorial/blob/master/kvm/kvm.conf)

**Comment by bryansteiner** [comment]
Closed due to no response from author with additional requested information.
