### ISSUE TITLE
qemu.d folder is not created.

### ISSUE THREAD

**Issue by symo521** [bryansteiner/gpu-passthrough-tutorial#37]
Hi I am using Archlinux.

I have downloaded the hooks helper and made it executable, however when I restart libvirtd, nothing happens. 
My mechanism for doing this is to run sudo systemctl restart libvirtd as the command in the guide does not work.
Is there something painfully obvious I'm missing, or is it simply not compatible with systemd? 
In this case am I able to manually put scripts here rather than using a tool?

**Comment by Abh15h3k** [comment]
`systemctl restart libvirtd` is correct for archlinux.

you have to manually create the `/etc/libvirt/qemu.d` directory structure
like so [VM Logistics](https://github.com/bryansteiner/gpu-passthrough-tutorial#----part-2-vm-logistics)
