### ISSUE TITLE
Bios version

### ISSUE THREAD

**Issue by xtreemrage** [bryansteiner/gpu-passthrough-tutorial#4]
Thanks for the tutorial, what is your mobo bios version?

**Comment by bryansteiner** [comment]
I'm running version F11. See [here](https://www.gigabyte.com/us/Motherboard/X570-AORUS-PRO-rev-1x/support#support-dl-bios).

**Comment by xtreemrage** [comment]
Is there a reason you are not on the latest? In this case F12e? Because I have read a lot of posts that some bios version will screw up the iommu groups, is this the case for F12e?

**Comment by bryansteiner** [comment]
I have no reason for being on the BIOS version that I'm on (F11) other than it being the latest version at the time I configured my setup. I have no issues with IOMMU grouping so I've had no reason to update again.
