### ISSUE TITLE
nvidia/nvidia-drm drivers do not automatically bind/unbind

### ISSUE THREAD

**Issue by rupiperse** [bryansteiner/gpu-passthrough-tutorial#7]
I have to manually load nvidia modules if I want to use them with the host. Do I have to modify my scripts somehow to enable drivers to load properly?

**Comment by bryansteiner** [comment]
Nvidia modules should be automatically loaded near boot-time if an Nvidia GPU is detected. Not sure why you have to manually load yours but please provide more information.

There should be no difference in the scripts you use. `bind.sh` unloads the Nvidia drivers before attaching vfio drivers but if you never loaded them (Nvidia) drivers in the first place, nothing should be affected.
