### ISSUE TITLE
iothreads not being used? 

### ISSUE THREAD

**Issue by RichGuk** [bryansteiner/gpu-passthrough-tutorial#9]
Came across this tutorial and noticed you're not using any of the iothreads (or I'm missing something).  Not an issue for your setup as you're passing the nvme controller. Just might be worth a mentioning that to make use of them you need to create either scsi controller and attach the disks to that, or use virtio-blk.

scsi:
```xml
<controller type='scsi' index='0' model='virtio-scsi'>
<driver queues='4' iothread='1'/>
<address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
</controller>
```
virtio-blk:
```xml
<domain>
  ....
  <devices>
    .....
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native' discard='unmap' iothread='1' queues='8'/>
      <source dev='/var/lib/libvirt/images/pool/win10.img'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    .....
  </devices>
  ....
</domain>
```

**Comment by bryansteiner** [comment]
Thank you for pointing this out! I completely overlooked it when writing the tutorial because I am indeed passing an entire nvme controller for my setup. I will update the tutorial to include this information.

Assuming I was instead using virtual-scsi, would the following configuration - **(1)** - be correct? How about the case where I use the older virtio-blk configuration instead - **(2)**? 

cpu:
```
<domain type="kvm">
      ...
      <iothreads>5</iothreads>
      <cputune>
           ...
           <iothreadpin iothread="1" cpuset="2-3">
           <iothreadpin iothread="2" cpuset="4-5"/>
           <iothreadpin iothread="3" cpuset="12-13"/>
           <iothreadpin iothread="4" cpuset="14-15"/>
           <iothreadpin iothread="5" cpuset="16-17"/>
      </cputune>
      ...
</domain>
```

**(1)** scsi:
```
<domain type="kvm">
      ...
      <devices>
            ...
            <controller type='scsi' index='0' model='virtio-scsi'>
                  <driver queues='10' iothread='5'/>
                  <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
            </controller>
            ...
      </devices>
</domain>
```
According to the [libvirt XML doc](https://libvirt.org/formatdomain.html#elementsControllers) it suggests the `queues` attribute be set to a value matching the number of vCPUs for best performance. In my case, that would be 10 vCPUs. And for the `iothread` attribute I set this to 5 to match the CPU tuning iothreads value.

**(2)** virtio-blk:
```
<domain type="kvm">
      ...
      <devices>
            ...
            <disk type='file' device='disk'>
                  <driver name='qemu' type='raw' cache='none' io='native' discard='unmap' iothread='5' queues='10'/>
                  <source dev='/var/lib/libvirt/images/pool/win10.img'/>
                  <target dev='vda' bus='virtio'/>
            </disk>
            ...
      </devices>
</domain>
```
Here we assume of course, that I have created and stored a virtual device image: `/var/lib/libvirt/images/pool/win10.img`

**Comment by RichGuk** [comment]
For **(1)** you don't need the iothread count on the disk attachment section, just on the controller. Here is mine, with block level disk:

```xml
<disk type='block' device='disk'>
  <driver name='qemu' type='raw' cache='none' io='threads'/>
  <source dev='/dev/disk/by-id/ata-CT1000MX500SSD1_1902E1E271CE'/>
  <target dev='sdc' bus='scsi'/>
  <address type='drive' controller='0' bus='0' target='0' unit='2'/>
</disk>
....
<controller type='scsi' index='0' model='virtio-scsi'>
  <driver queues='4' iothread='1'/>
  <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
</controller>
```

You can also only have one iothread per controller (virtio-blk creates a controller for each disk section I think), at least according to Arch wiki. I initially used scsi because it supported TRIM. However, it looks like virtio-blk does now (qemu 4.0+, guest linux kernel 5.0+, guest windows drivers 0.1.173+). I'm unsure of the performance difference.

Think virtio-blk version you would do:

```
<disk type='file' device='disk'>
  <driver name='qemu' type='raw' cache='none' io='native' discard='unmap' iothread='1' queues='8'/>
  <source dev='/var/lib/libvirt/images/pool/win10_1.img'/>
  <target dev='vda' bus='virtio'/>
</disk>
<disk type='file' device='disk'>
  <driver name='qemu' type='raw' cache='none' io='native' discard='unmap' iothread='2' queues='8'/>
  <source dev='/var/lib/libvirt/images/pool/win10_2.img'/>
  <target dev='vdb' bus='virtio'/>
</disk>
```

Remember for both during windows installation you need to add virtio driver iso as second CDROM so you can load the drivers.

**Comment by bryansteiner** [comment]
Thanks for the help. Closing the issue now that documentation has been updated accordingly.

**Comment by bryansteiner** [comment]
Thanks for the help. Closing the issue now that documentation has been updated accordingly.
